remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Domínio à Venda
description: O domínio www.clubedospets.com.br está disponível para compra.
show_downloads: false

github:
  is_project_page: false